apiVersion: v1
kind: Service
metadata:
  labels:
    name: segment-generator
  name: segment-generator
spec:
  ports:
    - name: segment-generator-tcp
      port: 8080
      targetPort: 8080
  selector:
    name: segment-generator
  type: NodePort